easy_admin:
    user:
        display_name: true
    entities:
        # List the entity class name you want to manage
        - App\Entity\Post
        - App\Entity\Comment
        - App\Entity\User
