version: '3'

services:
    mysql:
        image: mysql:5.7
        container_name: workshop-mysql
        ports: 
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: 'root'
            MYSQL_USER: 'user'
            MYSQL_PASSWORD: 'password'
            MYSQL_DATABASE: 'workshop'
        volumes:
        - db-volumes:/var/lib/mysql
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - '8080:80'
        environment:
            PMA_HOST: mysql
            MYSQL_ROOT_PASSWORD: 'root'

volumes:
    db-volumes: {}